apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: secretClientCertificates
  labels:
    key: secretClientCertificates
enabled: true
patches:
- target:
    kind: Deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: component
    spec:
      template:
        spec:
          containers:
          - name: main
            volumeMounts:
            - name: ca-certificates
              mountPath: "/etc/ssl/certs/ca-certificates.crt"
              subPath: ca-certificates.crt
          volumes:
          - name: ca-certificates
            secret:
              secretName: secrets
              items:
              - key: caCertificate
                path: "ca-certificates.crt"
- target:
    kind: Secret
    name: .*-secrets
  patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: component-secrets
    stringData:
      mongoDbUri: null
