apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: reloads-component-configs
enabled: true
patches:
- target:
    kind: SuperConfigMap
  patch: |-
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    metadata:
      name: reloads-configs
    data:
      keysUri: "http://$(PREFIX)-reloads-keys:8080/v1/keys/qlik.api.internal"
      qixSessionsUri: "http://$(PREFIX)-reloads-qix-sessions:8080"
      engineUri: "http://$(PREFIX)-reloads-engine:9076"
      usersUri: http://$(PREFIX)-reloads-users:8080
      tokenAuthUri: "http://$(PREFIX)-reloads-edge-auth:8080"
      natsStreamingClusterId: "$(PREFIX)-reloads-messaging-nats-streaming-cluster"