apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: reloads
enabled: true
patches:
  - path: deploymentJSON.yaml
    target:
      kind: Deployment
      name: reloads
  - path: deployment.yaml
