apiVersion: qlik.com/v1
kind: HelmValues
metadata:
  name: reloads 
releaseNamespace: $(NAMESPACE)
values:
  mongodb:
    enabled: false
  config:
    archive:
      enabled: false
  nats:
    enabled: false
    authEnabled: true
